/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * Type of ship
 */
export enum ShipType {
    SHIP_PROBE = 'SHIP_PROBE',
    SHIP_MINING_DRONE = 'SHIP_MINING_DRONE',
    SHIP_SIPHON_DRONE = 'SHIP_SIPHON_DRONE',
    SHIP_INTERCEPTOR = 'SHIP_INTERCEPTOR',
    SHIP_LIGHT_HAULER = 'SHIP_LIGHT_HAULER',
    SHIP_COMMAND_FRIGATE = 'SHIP_COMMAND_FRIGATE',
    SHIP_EXPLORER = 'SHIP_EXPLORER',
    SHIP_HEAVY_FREIGHTER = 'SHIP_HEAVY_FREIGHTER',
    SHIP_LIGHT_SHUTTLE = 'SHIP_LIGHT_SHUTTLE',
    SHIP_ORE_HOUND = 'SHIP_ORE_HOUND',
    SHIP_REFINING_FREIGHTER = 'SHIP_REFINING_FREIGHTER',
    SHIP_SURVEYOR = 'SHIP_SURVEYOR',
    SHIP_BULK_FREIGHTER = 'SHIP_BULK_FREIGHTER',
}
